apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: go-app
  template:
    metadata:
      labels:
        run: go-app
    spec:
      containers:
      - name: go-app
        image: gcr.io/anthos-cabral/go-app
---
apiVersion: v1
kind: Service
metadata:
  name: my-go-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    run: go-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: go-ing
spec:
  backend:
    serviceName: my-go-service # Name of the Service targeted by the Ingress
    servicePort: 80 # Should match the port used by the Service

