apiVersion: skaffold/v2alpha4
kind: Config
build:
  googleCloudBuild:
    projectId: anthos-cabral
  tagPolicy:
    dateTime: {}
  artifacts:
  - image: gcr.io/anthos-cabral/go-app
deploy:
  kubectl:
    manifests:
      - k8s-*
