apiVersion: skaffold/v2beta5
kind: Config
build:
  googleCloudBuild:
    projectId: YOUR-GCP-PROJECT-HERE
  tagPolicy:
    dateTime: {}
  artifacts:
  - image: gcr.io/anthos-cabral/go-app
deploy:
  kubectl:
    manifests:
      - k8s-*

